"""GPS C/A Gold-code PRN generator.

Each GPS L1 satellite broadcasts a unique 1023-chip spreading code (PRN) at
1.023 Mchip/s, repeating every millisecond.  The codes are generated by the
modulo-2 XOR of two 10-stage maximal-length LFSRs (G1 and G2):

    G1 polynomial:  1 + x³ + x¹⁰
    G2 polynomial:  1 + x² + x³ + x⁶ + x⁸ + x⁹ + x¹⁰

Different satellites use a different phase selection from G2 (two tap outputs
are XOR'd together), uniquely identifying each PRN.  The resulting 1023-chip
sequence has excellent auto-correlation and low cross-correlation properties.

Reference: IS-GPS-200, §3.3.2.3
"""

from __future__ import annotations

import numpy as np

from .constants import CA_CHIP_RATE, CA_CODE_LENGTH, PRN_G2_TAPS


def generate_ca_code(prn: int) -> np.ndarray:
    """Return the 1023-chip NRZ C/A code (±1 float32) for *prn* (1–32).

    Mapping: binary 0 → +1,  binary 1 → −1  (standard NRZ convention).
    """
    if prn not in PRN_G2_TAPS:
        raise ValueError(f"PRN {prn!r} is not in range 1–32")

    tap_a, tap_b = PRN_G2_TAPS[prn]

    # Both registers start at all-ones per the ICD
    g1: list[int] = [1] * 10
    g2: list[int] = [1] * 10
    chips = np.empty(CA_CODE_LENGTH, dtype=np.int8)

    for k in range(CA_CODE_LENGTH):
        # G1 output is taken from the LAST stage (stage 10, 0-indexed 9) per
        # IS-GPS-200 §3.3.2.3.  Reading an earlier stage (e.g. g1[0]) yields a
        # time-shifted G1 m-sequence — still a valid Gold code, so it "works"
        # in simulation (where the correlator uses the same wrong code) but
        # produces non-standard C/A codes that will not correlate against real
        # GPS satellites.  See tests/gps_sdr/test_prn_golden.py for the
        # IS-GPS-200 Table 3-Ia golden-vector check that pins this tap.
        chips[k] = g1[9] ^ g2[tap_a - 1] ^ g2[tap_b - 1]

        # G1 shift: feedback from taps 3, 10  (0-indexed: 2, 9)
        fb1 = g1[2] ^ g1[9]
        g1 = [fb1] + g1[:9]

        # G2 shift: feedback from taps 2,3,6,8,9,10  (0-indexed: 1,2,5,7,8,9)
        fb2 = g2[1] ^ g2[2] ^ g2[5] ^ g2[7] ^ g2[8] ^ g2[9]
        g2 = [fb2] + g2[:9]

    return (1 - 2 * chips).astype(np.float32)  # 0→+1, 1→−1


def resample_code(prn: int, sample_rate: float) -> np.ndarray:
    """Resample the C/A code from chip-rate to *sample_rate* Hz.

    Maps each output sample to the chip index it would land on at the given
    sample rate, producing a float32 ±1 array of length ⌊sample_rate × 1e-3⌋.
    """
    spc = int(round(sample_rate * 1e-3))
    chip_idx = (np.arange(spc) * CA_CHIP_RATE / sample_rate).astype(int) % CA_CODE_LENGTH
    return generate_ca_code(prn)[chip_idx]


def precompute_code_ffts(sample_rate: float) -> dict[int, np.ndarray]:
    """Pre-compute complex-conjugate FFTs of all 32 resampled C/A codes.

    Caching these avoids recomputing them inside the acquisition loop.
    Returns {prn: conj(FFT(code_sampled))} for prn in 1..32.
    """
    return {
        prn: np.conj(np.fft.fft(resample_code(prn, sample_rate))).astype(np.complex64)
        for prn in range(1, 33)
    }
