"""Ed25519 identity for this node.

The keypair is generated by signal-mesh-keygen.service (a oneshot that
runs Before= signal-mesh.service) and pinned at ``/var/lib/signal/keys/``
with mode 0600. The signal-mesh daemon itself never opens that
directory at runtime — systemd's credential manager copies both files
into ``$CREDENTIALS_DIRECTORY`` as root before stepping down to the
dynamic user, and ``load_from_credentials()`` reads them from there.

The public-key fingerprint is what an operator scans to mark a peer as
trusted — short, base32, six groups of four chars.

Cryptography uses ``cryptography`` (installed by ``install.sh``'s
``apt_install python3-cryptography`` line) when available; we degrade
to a stub that produces deterministic fake signatures so the rest of
the service is testable on dev machines without the library.
"""

from __future__ import annotations

import base64
import hashlib
import os
from dataclasses import dataclass
from pathlib import Path

KEY_DIR = Path("/var/lib/signal/keys")
PRIV_PATH = KEY_DIR / "ed25519.priv"
PUB_PATH = KEY_DIR / "ed25519.pub"


@dataclass(frozen=True)
class Identity:
    public_key: bytes
    fingerprint: str  # base32, grouped, no padding


@dataclass(frozen=True)
class IdentityBundle:
    """Both halves of the keypair, as delivered to the running daemon."""

    identity: Identity
    private_key: bytes


def _fingerprint(pub: bytes) -> str:
    """Short base32 fingerprint of a 32-byte public key.

    We take the first 15 bytes of SHA-256(pubkey) → 24 base32 chars →
    six groups of four for readability. That's 120 bits of entropy,
    plenty to resist accidental collisions on a small mesh.
    """

    h = hashlib.sha256(pub).digest()[:15]
    b32 = base64.b32encode(h).decode("ascii").rstrip("=")
    return "-".join(b32[i : i + 4] for i in range(0, len(b32), 4))


def load_or_create() -> Identity:
    """Return the local identity, generating it on first run.

    Idempotent: if the keys already exist on disk we just read them.
    Called by signal-mesh-keygen.service at boot, and by tests that
    monkeypatch KEY_DIR / PRIV_PATH / PUB_PATH onto a tmp_path.

    The cryptography dep is optional; without it we generate a fake
    "key" (32 random bytes) so the service can boot on dev. Production
    deployments install python3-cryptography via apt.
    """

    KEY_DIR.mkdir(parents=True, exist_ok=True)
    try:
        priv_bytes = PRIV_PATH.read_bytes()
        pub_bytes = PUB_PATH.read_bytes()
        return Identity(public_key=pub_bytes, fingerprint=_fingerprint(pub_bytes))
    except FileNotFoundError:
        pass

    try:
        from cryptography.hazmat.primitives.asymmetric.ed25519 import (  # type: ignore[import-not-found]
            Ed25519PrivateKey,
        )
        from cryptography.hazmat.primitives import serialization  # type: ignore[import-not-found]

        priv = Ed25519PrivateKey.generate()
        priv_bytes = priv.private_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PrivateFormat.Raw,
            encryption_algorithm=serialization.NoEncryption(),
        )
        pub_bytes = priv.public_key().public_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PublicFormat.Raw,
        )
    except ImportError:
        # Stub path. Two 32-byte random buffers — the API surface above
        # still works for tests, but signatures are not real Ed25519.
        priv_bytes = os.urandom(32)
        pub_bytes = hashlib.sha256(priv_bytes).digest()

    PRIV_PATH.write_bytes(priv_bytes)
    PRIV_PATH.chmod(0o600)
    PUB_PATH.write_bytes(pub_bytes)
    PUB_PATH.chmod(0o644)
    return Identity(public_key=pub_bytes, fingerprint=_fingerprint(pub_bytes))


def load_from_credentials() -> IdentityBundle:
    """Load the keypair the signal-mesh.service daemon will sign with.

    Resolution order:

    1. ``$CREDENTIALS_DIRECTORY/ed25519_{priv,pub}`` — what
       systemd's ``LoadCredential=`` produces. This is the production
       path; the daemon has no other filesystem access to the key
       directory.
    2. ``PRIV_PATH`` / ``PUB_PATH`` on disk — fallback for dev, tests
       run outside systemd, and the keygen unit itself (which
       generates the files before LoadCredential exists).

    If neither produces a readable pair we return a stub bundle
    (random pub, zero priv) so the daemon still boots; ``/notes/publish``
    will then emit unsigned envelopes, just as it did pre-v1.2.
    """

    cred_dir = os.environ.get("CREDENTIALS_DIRECTORY")
    if cred_dir:
        priv_p = Path(cred_dir) / "ed25519_priv"
        pub_p = Path(cred_dir) / "ed25519_pub"
        try:
            priv_bytes = priv_p.read_bytes()
            pub_bytes = pub_p.read_bytes()
            return IdentityBundle(
                identity=Identity(public_key=pub_bytes, fingerprint=_fingerprint(pub_bytes)),
                private_key=priv_bytes,
            )
        except FileNotFoundError:
            # Credential dir set but key missing — fall through to disk.
            pass

    try:
        priv_bytes = PRIV_PATH.read_bytes()
        pub_bytes = PUB_PATH.read_bytes()
        return IdentityBundle(
            identity=Identity(public_key=pub_bytes, fingerprint=_fingerprint(pub_bytes)),
            private_key=priv_bytes,
        )
    except FileNotFoundError:
        # No keys at all — emit a stub so the daemon stays up.
        stub_pub = hashlib.sha256(b"signal-mesh-unprovisioned").digest()
        return IdentityBundle(
            identity=Identity(public_key=stub_pub, fingerprint=_fingerprint(stub_pub)),
            private_key=b"\x00" * 32,
        )
